"""first commit

Revision ID: 14656cf6ea5b
Revises: None
Create Date: 2015-05-11 09:04:59.347596

"""

# revision identifiers, used by Alembic.
revision = '14656cf6ea5b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
