"""add upload model

Revision ID: 22b2a9fe0190
Revises: 3c3d8c95807a
Create Date: 2015-05-11 00:03:30.852637

"""

# revision identifiers, used by Alembic.
revision = '22b2a9fe0190'
down_revision = '3c3d8c95807a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('upload', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_upload_timestamp', 'upload', ['timestamp'], unique=False)
    op.create_index('ix_upload_upload', 'upload', ['upload'], unique=False)
    op.drop_column(u'posts', 'upload')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'posts', sa.Column('upload', sa.TEXT(), nullable=True))
    op.drop_index('ix_upload_upload', 'upload')
    op.drop_index('ix_upload_timestamp', 'upload')
    op.drop_table('upload')
    ### end Alembic commands ###
