"""user degree

Revision ID: 24b78daae841
Revises: 2666d5dc14d3
Create Date: 2015-05-24 20:58:35.477994

"""

# revision identifiers, used by Alembic.
revision = '24b78daae841'
down_revision = '2666d5dc14d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('degree', sa.Unicode(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'degree')
    ### end Alembic commands ###
