"""first commit

Revision ID: 2666d5dc14d3
Revises: None
Create Date: 2015-05-24 14:27:24.106179

"""

# revision identifiers, used by Alembic.
revision = '2666d5dc14d3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
