"""init db

Revision ID: 2df33569bf1a
Revises: None
Create Date: 2015-05-09 17:29:29.002456

"""

# revision identifiers, used by Alembic.
revision = '2df33569bf1a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
