"""first commit

Revision ID: 382dd7c079
Revises: None
Create Date: 2015-05-22 14:16:26.714907

"""

# revision identifiers, used by Alembic.
revision = '382dd7c079'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
