"""empty message

Revision ID: 383f6bb093bc
Revises: 51f5ccfba190
Create Date: 2015-04-29 09:05:40.457875

"""

# revision identifiers, used by Alembic.
revision = '383f6bb093bc'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
