"""change tags

Revision ID: 3c3d8c95807a
Revises: None
Create Date: 2015-05-10 15:46:48.138861

"""

# revision identifiers, used by Alembic.
revision = '3c3d8c95807a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
