"""empty message

Revision ID: 54e222e8692a
Revises: 383f6bb093bc
Create Date: 2015-04-30 13:35:15.448000

"""

# revision identifiers, used by Alembic.
revision = '54e222e8692a'
down_revision = '383f6bb093bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('upload', sa.UnicodeText(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'upload')
    ### end Alembic commands ###
